import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <h1>HEADLINE 1</h1>
      <h2>HEADLINE 2</h2>
      <h3>HEADLINE 3</h3>
      <h4>HEADLINE 4</h4>
      <p>Simply</p>
      <button className='cc__btn cc__btn--primary-color'>Primary</button>
      <button className='cc__btn cc__btn--secondary-color'>Secondary</button>
      <button className='cc__btn cc__btn--third-color'>Third</button>
    </>
  )
}
